CREATE TABLE DATOS_USUARIO(
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    APELLIDO_USUARIO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL
);

CREATE TABLE NITTABLA(
    NIT char(10) PRIMARY KEY,
    USUARIO_PROPIETARIO INT NOT NULL,
    FOREIGN KEY (USUARIO_PROPIETARIO) REFERENCES DATOS_USUARIO(ID_USUARIO)
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    MONTO DOUBLE NOT NULL,
    CANTIDAD INT NOT NULL,
    DESCUENTOMAX DOUBLE
);

CREATE TABLE FACTURA(
	ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
    MONTO DOUBLE NOT NULL,
    NIT char(10),
    FOREIGN KEY (NIT) REFERENCES NITTABLA(NIT)
);

CREATE TABLE DETALLE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FACTURA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CANTIDAD INT NOT NULL,
    DESCUENTO BOOLEAN NOT NULL,
    FOREIGN KEY ID_FACTURA REFERENCES FACTURA(ID_FACTURA),
    FOREIGN KEY ID_PRODUCTO REFERENCES PRODUCTO(ID_PRODUCTO)
);