use master
go

create database DB_BasePruebas
go

use DB_BasePruebas
go

create schema SCH_GENERAL
go

DROP TABLE SCH_GENERAL.TBL_USUARIOS
GO

CREATE TABLE SCH_GENERAL.TBL_USUARIOS(
	IDTUX TINYINT IDENTITY(1,1) PRIMARY KEY, -- ID USUARIO TABLA USUARIO
	NUTUX VARCHAR(15) NOT NULL, -- NOMBRE USUARIO TABLA USUARIO
	PATUX VARCHAR(15) NOT NULL, -- PRIMER APELLITO TABLA USUARIO
	SATUX VARCHAR(15) NULL, -- SEGUNDO APELLIDO TABLA USUARIO
	NTUXX VARCHAR(10) NULL, -- NIT TABLA USUARIOS
)
GO

CREATE PROCEDURE [SCH_GENERAL].[SP_Usuario_Index]
AS
BEGIN

	SELECT 
		IDTUX,
		NUTUX,
		PATUX,
		SATUX,
		NTUXX
	FROM [SCH_GENERAL].[TBL_USUARIOS]

END
GO

CREATE PROCEDURE [SCH_GENERAL].[SP_Usuario_Create]
(
	@NUTUX VARCHAR(15),
	@PATUX VARCHAR(15),
	@SATUX VARCHAR(15),
	@NTUXX VARCHAR(15)
)
AS
BEGIN
	INSERT INTO [SCH_GENERAL].[TBL_USUARIOS]
	(
		NUTUX,
		PATUX,
		SATUX,
		NTUXX
	) VALUES (
		@NUTUX,
		@PATUX,
		@SATUX,
		@NTUXX
	)
	SELECT SCOPE_IDENTITY()
END
GO


CREATE PROCEDURE [SCH_GENERAL].[SP_Usuario_Read]
(
	@IDTUX TINYINT
)
AS
BEGIN

	SELECT 
		IDTUX,
		NUTUX,
		PATUX,
		SATUX,
		NTUXX
	FROM [SCH_GENERAL].[TBL_USUARIOS]
	WHERE IDTUX = @IDTUX

END
GO

CREATE PROCEDURE [SCH_GENERAL].[SP_Usuario_Update]
(
	@IDTUX TINYINT,
	@NUTUX VARCHAR(15),
	@PATUX VARCHAR(15),
	@SATUX VARCHAR(15),
	@NTUXX VARCHAR(15)
)
AS
BEGIN
	UPDATE [SCH_GENERAL].[TBL_USUARIOS]
	SET 
		NUTUX = @NUTUX,
		PATUX = @PATUX,
		SATUX = @SATUX,
		NTUXX = @NTUXX
	WHERE IDTUX = @IDTUX
	SELECT 1
END
GO

CREATE PROCEDURE [SCH_GENERAL].[SP_Usuario_Delete]
(
	@IDTUX TINYINT
)
AS
BEGIN
	DELETE FROM [SCH_GENERAL].[TBL_USUARIOS]
	WHERE IDTUX = @IDTUX
	SELECT 1
END
GO